---
- name: my Cloud infra settings..
  hosts: all
  tasks:
  - name: Ping my hosts
    ansible.builtin.ping:

  - name: clear docker containers, images, volumes if exist
    become: yes
    become_method: sudo
    ansible.builtin.shell: |
      docker rm -f $(docker ps -a -q)
      docker rmi -f $(docker image ls -q)
      docker volume rm -f $(docker volume ls -q)
      docker network rm $(docker network ls -q)

      exit 0

  - name: Create wordpress Volume
    become: yes
    community.docker.docker_volume:
      name: wordpress_vol

  - name: Create mariadb Volume
    become: yes
    community.docker.docker_volume:
      name: mariadb_vol
  
  - name: Create phpMyAdmin Volume
    become: yes
    community.docker.docker_volume:
      name: phpmyadmin_vol

  - name: Create underlay network
    become: yes
    community.docker.docker_network:
      name: inception_network

  - name: Copy files to the remote machine
    become: yes
    become_method: sudo
    ansible.builtin.copy:
      src: /Users/aybouras/Desktop/ansible_digitalocean/inception
      dest: /home
      mode: preserve

  # - name: aaaaaaaaaaaaaaaa
  #   become: yes
  #   become_method: sudo
  #   ansible.builtin.shell: |
  #    export IP_ADDR=$(ip -4 -o addr show eth0 | awk '{print $4}' | awk 'FNR == 1 {print}' | awk '{split($0,tab,"/"); print tab[1]}')
  #    echo $IP_ADDR > /home/IP_ADDR.txt

  #    exit 0
  

  - name: build nginx image from the local Dockerfile
    become: yes
    become_method: sudo
    community.docker.docker_image:
      name: nginx
      source: build
      build:
        path: /home/inception/nginx
      state: present

  - name: run nginx container
    become: yes
    community.docker.docker_container:
      image: nginx
      name: nginx
      ports:
        - "8080:8080"
        - "443:443"
      networks:
        - name: inception_network
      restart_policy: always
      state: started
      env_file: /home/inception/.env
      volumes:
        - wordpress_vol:/var/www/wordpress
        - phpmyadmin_vol:/var/www/phpmyadmin

  - name: build mariadb image from the Dockerfile
    become: yes
    become_method: sudo
    community.docker.docker_image:
      name: mariadb
      source: build
      build:
        path: /home/inception/mariadb
      state: present

  - name: run mariadb container
    become: yes
    community.docker.docker_container:
      image: mariadb
      name: mariadb
      ports:
        - "3306:3306"
      networks:
        - name: inception_network
      restart_policy: always
      state: started
      env_file: /home/inception/.env
      volumes:
        - mariadb_vol:/var/lib/mysql

  - name: build wordpress image from the Dockerfile
    become: yes
    become_method: sudo
    community.docker.docker_image:
      name: wordpress
      source: build
      build:
        path: /home/inception/wordpress
      state: present

  - name: Getting SSH_CONNECTION
    ansible.builtin.shell: echo $SSH_CONNECTION | awk '{print $3}'
    register: ip_var

  - name: run wordpress container
    become: yes
    community.docker.docker_container:
      image: wordpress
      name: wordpress
      ports:
        - "9000:9000"
      networks:
        - name: inception_network
      restart_policy: always
      state: started
      env:
          IP_ADDR: "{{ ip_var.stdout }}"
      env_file: /home/inception/.env
      volumes:
        - wordpress_vol:/var/www/wordpress

  # - name: remove 'Proudly powered by WordPress' from footer
  #   ansible.builtin.shell: sed -i "s/'footer-default',/ /" /var/lib/docker/volumes/wordpress_vol/_data/wp-content/themes/twentytwentytwo/inc/block-patterns.php

  - name: build phpMyAdmin image from the Dockerfile
    become: yes
    become_method: sudo
    community.docker.docker_image:
      name: phpmyadmin
      source: build
      build:
        path: /home/inception/phpmyadmin
      state: present

  - name: run phpMyAdmin container
    become: yes
    community.docker.docker_container:
      image: phpmyadmin
      name: phpmyadmin
      ports:
        - "7000:7000"
      networks:
        - name: inception_network
      restart_policy: always
      state: started
      env_file: /home/inception/.env
      volumes:
        - phpmyadmin_vol:/var/www/phpmyadmin
  
  - name: Delete content & directory
    become: yes
    ansible.builtin.file:
      path: /home/inception
      state: absent